name: GGSpawnGSG
version: 1.4.2
api-version: 1.13
main: dev.timecoding.ggspawngsg.GGSpawnGSG
website: timecoding.de

commands:
  spawnplot:
    aliases:
      - sp
      - ggspawngsg
    description: Der Hauptcommand für das GGSpawnGSG Plugin!